[package]
name = "raytracer"
version = "0.1.0"
authors = ["Colin Tan <colintan95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.9"
num = "0.3.0"
